DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    super_id BIGINT(20) NULL DEFAULT NULL COMMENT '上级ID',
    create_time DATETIME DEFAULT NOW() COMMENT '创建时间',
    update_time DATETIME DEFAULT NOW() COMMENT '修改时间',
    version INT(11) DEFAULT 1 COMMENT '版本',
    deleted INT(1) DEFAULT 0 COMMENT '逻辑删除(0未删除, 1已删除)',
    CONSTRAINT super_fk FOREIGN KEY (super_id) REFERENCES user(id),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;